package main

type AutoGenerated struct {
	Server struct {
		Host string `yaml:"host"`
		SSH  struct {
			Port     int    `yaml:"port"`
			Username string `yaml:"username"`
			KeyPath  string `yaml:"key_path"`
		} `yaml:"ssh"`
		Ports struct {
			HTTP         int `yaml:"http"`
			Grpc         int `yaml:"grpc"`
			Registration int `yaml:"registration"`
		} `yaml:"ports"`
		Routing struct {
			PathMatching struct {
				CaseSensitive bool   `yaml:"case_sensitive"`
				TrailingSlash string `yaml:"trailing_slash"`
			} `yaml:"path_matching"`
			Paths []struct {
				Pattern      string `yaml:"pattern"`
				Description  string `yaml:"description"`
				RequiredAuth bool   `yaml:"required_auth"`
			} `yaml:"paths"`
		} `yaml:"routing"`
	} `yaml:"server"`
	Client struct {
		ID    string `yaml:"id"`
		Ports struct {
			HTTPStart   int `yaml:"http_start"`
			TunnelStart int `yaml:"tunnel_start"`
		} `yaml:"ports"`
		Registration struct {
			RetryInterval int `yaml:"retry_interval"`
			Timeout       int `yaml:"timeout"`
			Paths         []struct {
				Path        string `yaml:"path"`
				Description string `yaml:"description"`
				Metadata    []struct {
					Version  string `yaml:"version"`
					Provider string `yaml:"provider"`
				} `yaml:"metadata,omitempty"`
			} `yaml:"paths"`
		} `yaml:"registration"`
		Heartbeat struct {
			Interval int `yaml:"interval"`
			Timeout  int `yaml:"timeout"`
		} `yaml:"heartbeat"`
	} `yaml:"client"`
}
